### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by dannisonarias**
Completed Page layout and Styling. Fixed links not working above the footer, a link added for the play button, added border-radius for nav.

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
## Hi @dannisonarias,
- Your project looks good, very similar to the apple page and you have a descriptive readme file. 👏
However, there are a few things that you need to fix so that you can meet all the requirements.

**Bottom**
- Each element of the four images in a row right above the footer should be links just like on the apple page.

**General**
- Your Pull Request should have a short description of what you have implemented so far, kindly update it [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).
- Please make sure your commits descriptive as [mentioned in Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png), don't use general commits like _general work, css, html_

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review.

## Status: Changes Required

_Feel free to reach out to me on slack (Fatima) If you have any questions, I'd be happy to help 😀_

**Comment by shshamim63** [comment]
## Status :white_check_mark: [Changes Required] :white_check_mark: 
___
Hi @dannisonarias :wave: 
Repository contains descriptive readme, code looks neat and clean, items of the page rendering almost same as the original one. Awesome job :clap: . But there is a simple issue that is blocking me to approve this project. Please follow the instruction below.
___
### [Mandatory Changes]
___
1. Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright). I can see some errors in there.
image
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — APPROVED** [review]
### Good job guys, finally you got it right

### - I approve this project

### You can move on to the next project. I wish you all the best. Happy coding!

**Pull request merged**
